### ISSUE TITLE
Actualización de Splash Art para MoogooseFeast

### ISSUE THREAD

**Issue by SProyect** [SubaruDev0/MoogooseFeast_Game_Godot#1]
- Este issue es para adjuntar la nueva actualización del splash art para MoogooseFeast. 

### Cambios Realizados ### 
- Ajuste de la paleta de colores para mayor coherencia.
- Cambio del frame de correr para hacerlo coherente y fiel al personaje principal

Por favor, revisen el nuevo splash art adjunto para su consideración.
![1723217812892](https://github.com/user-attachments/assets/7f9e2a22-d4e6-40d0-be08-3f521c722750) ![1723217823483](https://github.com/user-attachments/assets/db1ff77e-94d6-4883-b19d-fd1c2374a773) ![1723217829805](https://github.com/user-attachments/assets/2fbfb4c9-b20c-447e-b4cd-8b262bdf9312) ![1723217835091](https://github.com/user-attachments/assets/8bbaf722-644a-49e8-9673-1fb4055fb6a8) ![1723217845011](https://github.com/user-attachments/assets/78104f02-9c68-4e0d-94e5-b979dd9fbf4f) ![1723217851468](https://github.com/user-attachments/assets/380acfdc-74d3-4fef-83e7-56cd5caca142)

**Comment by SubaruDev0** [comment]
Ta goood

**Comment by SubaruDev0** [comment]
> * Este issue es para adjuntar la nueva actualización del splash art para MoogooseFeast.
> 
> ### Cambios Realizados
> * Ajuste de la paleta de colores para mayor coherencia.
> * Cambio del frame de correr para hacerlo coherente y fiel al personaje principal
> 
> Por favor, revisen el nuevo splash art adjunto para su consideración. ![1723217812892](https://private-user-images.githubusercontent.com/168592934/356919376-7f9e2a22-d4e6-40d0-be08-3f521c722750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MjgxNTcsIm5iZiI6MTcyMzQyNzg1NywicGF0aCI6Ii8xNjg1OTI5MzQvMzU2OTE5Mzc2LTdmOWUyYTIyLWQ0ZTYtNDBkMC1iZTA4LTNmNTIxYzcyMjc1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQwMTU3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjEyOTUyZTc0YTVkODhmMjYwNTVmNjQyNTM3N2QzZmVkODA1NjQ1NTQyMThmN2M1ZWMwOGFlMjY3NDE1Y2FlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UqnH4FTG2-e1LcSj1z8AuHDrpg0qKkSTr6pdv7B7XM0) ![1723217823483](https://private-user-images.githubusercontent.com/168592934/356919378-db1ff77e-94d6-4883-b19d-fd1c2374a773.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MjgxNTcsIm5iZiI6MTcyMzQyNzg1NywicGF0aCI6Ii8xNjg1OTI5MzQvMzU2OTE5Mzc4LWRiMWZmNzdlLTk0ZDYtNDg4My1iMTlkLWZkMWMyMzc0YTc3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQwMTU3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGEzZTc2ZTY3ZWIyZWExNGY3YTE0MjFkZjM4MTZiNWFmNTM0M2I1NjEwODY3YmVmMGVmMDJkYzVjMDgxYWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xLntCjM7aHdJdMtOumIdRv1MgKlqeeGKtPO4TAECF5g) ![1723217829805](https://private-user-images.githubusercontent.com/168592934/356919379-2fbfb4c9-b20c-447e-b4cd-8b262bdf9312.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MjgxNTcsIm5iZiI6MTcyMzQyNzg1NywicGF0aCI6Ii8xNjg1OTI5MzQvMzU2OTE5Mzc5LTJmYmZiNGM5LWIyMGMtNDQ3ZS1iNGNkLThiMjYyYmRmOTMxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQwMTU3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWM1OTZkYjNmNzMwYWNlOTgwZDE1ZWNlMjhlMzI1ZjVmZmEzMzI4YTcyYmFmMGI3OTFkNDQ1NDQyYTI4YWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.noOruCmokWpZg-wVamcEYfPtM7Iu7KiS4VYaEWFigbM) ![1723217835091](https://private-user-images.githubusercontent.com/168592934/356919382-8bbaf722-644a-49e8-9673-1fb4055fb6a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MjgxNTcsIm5iZiI6MTcyMzQyNzg1NywicGF0aCI6Ii8xNjg1OTI5MzQvMzU2OTE5MzgyLThiYmFmNzIyLTY0NGEtNDllOC05NjczLTFmYjQwNTVmYjZhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQwMTU3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGY3MmIwZjA0NzhiNDk5YTAwZGIyOGU4MTlmMDg1Y2NiMTFjZTA4Yjk0ZTE3ZDNkYjk3ZDIxYWY1ZjJhMzk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5n111P6o9jYrtTKYJvzKA8_FAZoOk2eUPgG3vSpsMD8) ![1723217845011](https://private-user-images.githubusercontent.com/168592934/356919384-78104f02-9c68-4e0d-94e5-b979dd9fbf4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MjgxNTcsIm5iZiI6MTcyMzQyNzg1NywicGF0aCI6Ii8xNjg1OTI5MzQvMzU2OTE5Mzg0LTc4MTA0ZjAyLTljNjgtNGUwZC05NGU1LWI5NzlkZDlmYmY0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQwMTU3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTBmMTZmZTRjZjEwOWMzMjE3ODBiZDNiOThiZGNmODMwZDE0MTlmYjBkNjk5Njg2MDZjMTQ4OGYyMWJmYTJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M8WJirUQtaex8wRWhkPLE_uX43KJKRvOBOdHQhnSyNU) ![1723217851468](https://private-user-images.githubusercontent.com/168592934/356919386-380acfdc-74d3-4fef-83e7-56cd5caca142.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MjgxNTcsIm5iZiI6MTcyMzQyNzg1NywicGF0aCI6Ii8xNjg1OTI5MzQvMzU2OTE5Mzg2LTM4MGFjZmRjLTc0ZDMtNGZlZi04M2U3LTU2Y2Q1Y2FjYTE0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQwMTU3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGUwYTk5OTkyZDI5NTllZTA0ZjJhMjg2Y2FiNWI0MWY0YzE4MWY3Zjc1OWE0MzkxYTg0MzdmMjk0OWRhMjNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FNNn6KruV1i9CNxQag0XHwPLzaaS-YpI79AWQNuVUNA)
